export const symbols = {
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  house: "house",
  // collection: "collection",
  // infoCircle: "info-circle",
  // transparency: "transparency",
  // journalCheck: "journal-check",
  // journalPlus: "journal-plus",
  // lightningCharge: "lightning-charge",
  // peopleCircle: "people-circle",
  // personCheck: "person-check",
  // search: "search",
  // toggles2: "toggles2",
  // pencilFill: "pencil-fill",
  sliders: "sliders",
  coin: "coin",
  wallet: "wallet",
  bank2: "bank2",
  arrowUpRight: "arrow-up-right",
  chartFill: "chart-fill",
  menu: "menu",
  // calendar3: "calendar3",
  gearFill: "gear-fill",
  nodePlusFill: "node-plus-fill",
}
